#! /bin/sh

bspc config pointer_modifier mod1
bspc config focus_follows_pointer true

bspc monitor -d I II III IV V

bspc config border_width 1
bspc config focused_border_color \#7fa2ac
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

#auto-start

picom --experimental-backend &
~/.config/polybar/launch.sh &
feh --bg-fill ~/.Backgrounds/"buho.webp"
sxhkd &
xsetroot -cursor_name left_ptr

# Configuration  Redshift
redshift -l 11.00:-74.24 -t 5400:3400 -g 0.8 -m randr -v &
